server:
  port: 8441
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org.fintech: debug